version: '3'

services:
  controls:
    image: quay.io/mrizzi/poc-controls:add-metadata-to-hal-native
    ports:
      - 8080:8080
    environment:
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/controls_db
      QUARKUS_OIDC_AUTH_SERVER_URL: http://localhost:8180/auth/realms/konveyor
      QUARKUS_OIDC_CLIENT_ID: controls-api
      QUARKUS_OIDC_CREDENTIALS_SECRET: secret


