name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn test --coverage --watchAll=false
      - uses: codecov/codecov-action@v1
        with:
          flags: unitests

  e2e:
    needs: [unit-test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]
    services:
      keycloak:
        image: quay.io/keycloak/keycloak:12.0.1
        ports:
          - 8180:8080
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        options: >-
          --health-cmd "curl --fail http://localhost:8080/auth || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Keycloak Admin CLI
        uses: carlosthe19916/keycloak-action@0.4
        with:
          server: http://keycloak:8080/auth
          username: admin
          password: admin
          kcadm: create realms -f konveyor-realm.json
      - run: yarn install
      - run: yarn build:instrumentation
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: false
          start: yarn run ui:start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          config: pageLoadTimeout=100000
          browser: ${{ matrix.browser }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: e2e-screenshots-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: e2e-videos-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/videos
      - uses: codecov/codecov-action@v1
        with:
          flags: e2etests

  container-images:
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'carlosthe19916' }}
    runs-on: ubuntu-latest
    needs: [unit-test, e2e]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn build      
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: quay.io
          name: carlosthe19916/controls-ui
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          dockerfile: Dockerfile
          snapshot: false
          tags: "master"
