name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # unit-test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [10.x, 12.x, 14.x]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: yarn install
  #     - run: yarn build
  #     - run: yarn test --coverage --watchAll=false
  #     - uses: codecov/codecov-action@v1
  #       with:
  #         flags: unitests

  e2e:
    # needs: [unit-test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: docker-compose --verbose up
      - name: wait-on
        run: docker ps -a && sleep 50s
      - name: wait-on
        run: docker ps -a
      - run: yarn install
      - run: yarn build:instrumentation
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: false
          start: yarn run ui:start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          config: pageLoadTimeout=100000
          browser: ${{ matrix.browser }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: e2e-screenshots-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: e2e-videos-${{ matrix.os }}-${{ matrix.browser }}
          path: cypress/videos
      - uses: codecov/codecov-action@v1
        with:
          flags: e2etests

  # container-images:
  #   if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'carlosthe19916' }}
  #   runs-on: ubuntu-latest
  #   needs: [unit-test, e2e]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12.x
  #     - run: yarn install
  #     - run: yarn build      
  #     - name: Push to Quay.io
  #       uses: elgohr/Publish-Docker-Github-Action@master
  #       with:
  #         registry: quay.io
  #         name: carlosthe19916/controls-ui
  #         username: ${{ secrets.QUAYIO_USERNAME }}
  #         password: ${{ secrets.QUAYIO_PASSWORD }}
  #         dockerfile: Dockerfile
  #         snapshot: false
  #         tags: "master"
